### ISSUE TITLE
Schema

### ISSUE THREAD

**Issue by simcha-c** [davidrichard23/unlikelihood#3]
Hey David,

Here are a few updates for your schema. These are small changes, so really great job on the work you put in.

1. The table names should be lowercase and pluralized since that is how we reference tables.

**user table**

2. If the user can log in using their username, `username` needs to be unique as well.

**assets table**

3. can we change the `assets` table name to `stocks`? I think that is clearer as to what it is. Otherwise, it looks great!

**portfolios table**

4. what is `shares`?

Everything else looks good!
Simcha

**Comment by davidrichard23** [comment]
1. 👍
2. 👍
3. I was thinking that since you can buy cryptocurrencies, assets would be a more fitting name, but I will rename it to stocks.
4. Shares is the amount of shares the user owns of the particular asset/stock

**Comment by simcha-c** [comment]
If you think that `assets` is a better name for the table, that works too... 👍
